### ISSUE TITLE
Colours after egypt not working

### ISSUE THREAD

**Issue by sushil-mathew** [friosavila/stataviz#1]
Hello!
Thanks for the brilliant package. I've been waiting for these colours to come on stata for a while now. 
Just something that I've been having trouble with: I'm not able to run color_style name, graph for any "name" after egypt. But everything before egypt works. 
It returns the following error:
color specification 'homer1' is invalid
r(3498);

**Comment by friosavila** [comment]
can you tell me if you have a mac or a PC? and is this with Stata 16 or 17?

**Comment by sushil-mathew** [comment]
I have Windows 10, and this is on stata 17

**Comment by friosavila** [comment]
that is quite odd
So, could you do the following.
1) reinstall colorspace and palette
net install palettes , replace from("
https://raw.githubusercontent.com/benjann/palettes/master/")
net install colrspace, replace from("
https://raw.githubusercontent.com/benjann/colrspace/master/")

2) reinstall color_style
ssc install color_style, replace

3) reset all options in stata:
cscript

4) retry the following:
color_style, list
color_style homer1
color_style homer1, showcase

I hope this fixes the problem. if not, please let me know

**Comment by sushil-mathew** [comment]
Ah this works now! Seems like my palettes and colrspace were probably not updated then. Sorry to bother you with this. And thanks again for the package and your help!

**Comment by friosavila** [comment]
Awesome! Not a bother. Its good to figure out this bugs!
